### ISSUE TITLE
HtmlWebpackPlugin 问题

### ISSUE THREAD

**Issue by uyoungco** [JesseZhao1990/multipage-webpack-scaffolding#21]
在也HTML上并没有获取到title
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>
  </body>
</html>
```
我顺着配置找到了utils.js 修改成下面这样
```javascript
webpackConfig.plugins.push(new HtmlWebpackPlugin({
        title: page.name,
        filename: path.join(__dirname, `/dist/${page.name}.html`),
        template,
        inject: true,
        chunks: [`${page.name}Top`, page.name],
        inlineSource: '.(js|style)$',
        chunksSortMode: 'dependency',
        ...options
      }))
```
一样无法再对应的html获取到  htmlWebpackPlugin.options.title

**Comment by uyoungco** [comment]
```javascript
{
        test: /\.html$/,
        loader: 'html-withimg-loader',
        include: [path.join(__dirname, './src')],
        options: {
          limit: 10000,
          name: 'static/img/[name].[hash:7].[ext]'
        }
      },
```
跟这个有关系  解决办法再找

**Comment by uyoungco** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/youngu/.nvm/versions/node/v10.14.1/bin/node',
1 verbose cli   '/Users/youngu/.nvm/versions/node/v10.14.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.14.4
3 info using node@v10.14.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle mutipages@1.0.0~prebuild: mutipages@1.0.0
6 info lifecycle mutipages@1.0.0~build: mutipages@1.0.0
7 verbose lifecycle mutipages@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle mutipages@1.0.0~build: PATH: /Users/youngu/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/.bin:/Users/youngu/.yarn/bin:/Users/youngu/.config/yarn/global/node_modules/.bin:/Users/youngu/.nvm/versions/node/v10.14.1/bin:/Users/youngu/.jenv/shims:/Users/youngu/.jenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/.bin:/Users/youngu/Documents/private/javaUtil/apache-maven-3.6.3/bin:/Users/youngu/Documents/private/javaUtil/gradle-6.0.1/bin
9 verbose lifecycle mutipages@1.0.0~build: CWD: /Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding
10 silly lifecycle mutipages@1.0.0~build: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=production webpack --config webpack.config.prod.js' ]
11 silly lifecycle mutipages@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle mutipages@1.0.0~build: Failed to exec build script
13 verbose stack Error: mutipages@1.0.0 build: `cross-env NODE_ENV=production webpack --config webpack.config.prod.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/youngu/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/youngu/.nvm/versions/node/v10.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid mutipages@1.0.0
15 verbose cwd /Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding
16 verbose Darwin 19.0.0
17 verbose argv "/Users/youngu/.nvm/versions/node/v10.14.1/bin/node" "/Users/youngu/.nvm/versions/node/v10.14.1/bin/npm" "run" "build"
18 verbose node v10.14.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 2
22 error mutipages@1.0.0 build: `cross-env NODE_ENV=production webpack --config webpack.config.prod.js`
22 error Exit status 2
23 error Failed at the mutipages@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
头疼

**Comment by uyoungco** [comment]
```
ERROR in ./src/pages/home/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ReferenceError: window is not defined
    at /Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/style-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/css-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/sass-loader/dist/cjs.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/src/pages/home/index.scss:235:2
    at /Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/style-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/css-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/sass-loader/dist/cjs.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/src/pages/home/index.scss:224:46
    at module.exports.module.exports (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/style-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/css-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/sass-loader/dist/cjs.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/src/pages/home/index.scss:289:88)
    at Object.<anonymous> (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/style-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/css-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/sass-loader/dist/cjs.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/src/pages/home/index.scss:107:36)
    at __webpack_require__ (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/style-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/css-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/sass-loader/dist/cjs.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/src/pages/home/index.scss:21:30)
    at /Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/style-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/css-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/sass-loader/dist/cjs.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/src/pages/home/index.scss:85:18
    at Object.<anonymous> (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/style-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/css-loader/index.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/sass-loader/dist/cjs.js!/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/src/pages/home/index.scss:88:10)
    at Module._compile (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at evalModuleCode (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/mini-css-extract-plugin/dist/loader.js:61:10)
    at childCompiler.runAsChild (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/mini-css-extract-plugin/dist/loader.js:166:21)
    at compile (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/webpack/lib/Compiler.js:343:11)
    at hooks.afterCompile.callAsync.err (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/webpack/lib/Compiler.js:678:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/webpack/lib/Compilation.js:1423:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/webpack/lib/Compilation.js:1414:32)
    at _err1 (eval at create (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at taskRunner.run (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/terser-webpack-plugin/dist/index.js:321:9)
    at TaskRunner.run (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/terser-webpack-plugin/dist/TaskRunner.js:48:7)
    at TerserPlugin.optimizeFn (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/terser-webpack-plugin/dist/index.js:227:18)
    at _next0 (eval at create (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at _err0 (eval at create (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at /Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/uglifyjs-webpack-plugin/dist/index.js:287:11
    at Runner.runTasks (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/uglifyjs-webpack-plugin/dist/uglify/Runner.js:67:9)
    at UglifyJsPlugin.optimizeFn (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/uglifyjs-webpack-plugin/dist/index.js:198:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/webpack/lib/Compilation.js:1409:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/Users/youngu/Documents/private/Xiaogounews/multipage-webpack-scaffolding/node_modules/webpack/lib/Compilation.js:1405:32)
 @ ./src/pages/home/index.js 3:0-22
```
头疼 一直一直有问题 折腾死了

**Comment by uyoungco** [comment]
我就想不明白scss为什么一直报错
